# -*- coding: utf-8 -*-
"""Practical_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1resOkWBNo6gzImXfAtfvuuihYypLTPpp
"""

import ee

import geemap

ee. Authenticate()
ee. Initialize(project="preeti-ee")

map= geemap.Map(ee_initilize=False)
map



Taluk = ee.FeatureCollection("projects/preeti-ee/assets/Taluk_Boundary")
map.addLayer(Taluk,{},'Taluk_Boundary')
map



Waterbody= ee.FeatureCollection("projects/preeti-ee/assets/Waterbody")
map.addLayer(Waterbody,{},'Waterbody')

State_Highway = ee.FeatureCollection("projects/preeti-ee/assets/State_Highway")
map.addLayer(State_Highway,{},'State_Highway')

Settlements= ee.FeatureCollection("projects/preeti-ee/assets/Settlements")
map.addLayer(Settlements,{},'Settlements')

National_Highway= ee.FeatureCollection("projects/preeti-ee/assets/National_Highway")
map.addLayer(National_Highway,{},'National_Highway')

Forest= ee.FeatureCollection("projects/preeti-ee/assets/Forest")
map.addLayer(Forest,{},'Forest')

Agriculture= ee.FeatureCollection("projects/preeti-ee/assets/Agriculture")
map.addLayer(Agriculture,{},'Agriculture')

Railways= ee.FeatureCollection("projects/preeti-ee/assets/Railways")
map.addLayer(Railways,{},'Railways')

Waterways= ee.FeatureCollection("projects/preeti-ee/assets/Waterways")
map.addLayer(Waterways,{},'Waterways')

map.centerObject(Taluk,11)
map

import geopandas as gpd

gjs = gpd.read_file("/content/Taluk_Boundary.shp")

gjs.to_file("Taluk_Boundary.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/Agriculture_OSM.shp")

gjs.to_file("Agriculture.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/Forest_OSM.shp")

gjs.to_file("Forest.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/NationalHighway_OSM.shp")

gjs.to_file("Nationalhighway.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/Railways_OSM.shp")

gjs.to_file("Railway.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/StateHighway_OSM.shp")

gjs.to_file("Satehighway.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/Water_OSM.shp")

gjs.to_file("Waterbody.geojson",driver="GeoJSON")

gjs = gpd.read_file("/content/Waterways_OSM.shp")

gjs.to_file("Waterways.geojson",driver="GeoJSON")

"""** EXERCISE** **2**"""

import ee

import geemap

ee.Authenticate()
ee.Initialize(project='preeti-ee')

import geemap as map

Map = geemap.Map()
Map

Taluk = ee.FeatureCollection("projects/preeti-ee/assets/SUBDISTRICT_BOUNDARY")
Map.addLayer(Taluk, {}, "Taluk")
Map.centerObject(Taluk,11)
Map

Map = geemap.Map()
DEM= ee.ImageCollection("JAXA/ALOS/AW3D30/V4_1")
Taluk_DEM= DEM.filterBounds(Taluk).mosaic().clip(Taluk)
Map.addLayer(Taluk_DEM,{},"DEM")
Map.centerObject(Taluk,11)
Map

DEM= ee.ImageCollection("JAXA/ALOS/AW3D30/V4_1").select("DSM")
Taluk_DEM = DEM.filterBounds(Taluk).mosaic().clip(Taluk)
Map.addLayer(Taluk_DEM,{'min': 0, 'max': 116, 'palette': ['#fff7ec', '#fee8d0', '#fdd49e', '#fdbb84', '#fc8d59', '#ef6548', '#d7301f', '#990000']},"DEM")
Map

Map = geemap.Map()
NDVI= ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI")
Taluk_NDVI= NDVI.filterBounds(Taluk).mosaic().clip(Taluk)
Map.addLayer(Taluk_NDVI,{'min': -0.8, 'max': 1, 'palette': ['#f7fcb9', '#d9f0a3', '#addd8e', '#78c679', '#41ab5d', '#238443', '#006837', '#004529']},"NDVI")
Map.centerObject(Taluk,11)
Map

Export_DEM = ee.batch.Export.image.toDrive(image=Taluk_DEM,
                                           description="DEM_Export",
                                           folder="GEE_Exports",
                                           fileNamePrefix="DEM",
                                           region=Taluk.geometry().bounds(),
                                           scale=30,
                                           crs="EPSG:4326",
                                           maxPixels=1e13
                                           )
Export_DEM.start()

Taluk_NDVI = NDVI.mean()

Taluk_NDVI = Taluk_NDVI.clip(Taluk.geometry())

Taluk_NDVI = Taluk_NDVI.rename('NDVI')

Export_NDVI = ee.batch.Export.image.toDrive(image=Taluk_NDVI,
                                           description="NDVI_Export",
                                           folder="GEE_Exports",
                                           fileNamePrefix="NDVI",
                                           region=Taluk.geometry().bounds(),
                                           scale=30,
                                           crs="EPSG:4326",
                                           maxPixels=1e13)
Export_NDVI.start()

